//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductRatingAndReview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AggregateReviewTB
    {
        public int AggregateId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> AggregateStar { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual CategoryTB CategoryTB { get; set; }
        public virtual ProductTB ProductTB { get; set; }
    }
}
