//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductRatingAndReview.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductReviewDBEntities : DbContext
    {
        public ProductReviewDBEntities()
            : base("name=ProductReviewDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AggregateReviewTB> AggregateReviewTBs { get; set; }
        public virtual DbSet<CategoryTB> CategoryTBs { get; set; }
        public virtual DbSet<ProductTB> ProductTBs { get; set; }
        public virtual DbSet<ReviewTB> ReviewTBs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserTB> UserTBs { get; set; }
    }
}
