//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductRatingAndReview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewTB
    {
        public int ReviewId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> NumberOfStar { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ProductTB ProductTB { get; set; }
        public virtual UserTB UserTB { get; set; }
    }
}
